name: Deploy to GitHub Pages
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # Trigger on version tags like v1.0.0

jobs:
  build-prod-job:
      runs-on: ubuntu-latest
      steps:
        - name: Clone repository
          uses: actions/checkout@v6
        - name: Setup Node.js version 24.x
          uses: actions/setup-node@v6
          with:
            node-version: '24.x'
            cache: 'npm'
        - name: Install dependencies and build
          run: npm ci # clean install แทน npm install
        - name: Build the project
          run: npm run build